from pygsheets.exceptions import (
    IncorrectCellLabel as IncorrectCellLabel,
    InvalidArgumentValue as InvalidArgumentValue,
)

def finditem(func, seq): ...
def numericise(value, empty_value: str = ""): ...
def numericise_all(input, empty_value: str = ""): ...
def is_number(n): ...
def format_addr(addr, output: str = "flip"): ...
def fullmatch(regex, string, flags: int = 0): ...
def format_color(data, to: str = "dict"): ...
def get_color_style(color_obj): ...
def get_boolean_condition(type, values): ...
def batchable(func): ...
def allow_gridrange(method): ...
