name: myTransactions Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - '.github/**'
              - '*.py'
              - 'Dockerfile'
              - '*.toml'
              - 'Pipfile*'
              - '*.sh'
  build:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.12.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv wheel
      
      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          python -m pipenv install --deploy --dev
      
      - name: Run quality checks
        run: |
          python -m pipenv run black . --check
          python -m pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
          python -m pipenv run mypy .

      - name: Run unit tests with coverage
        run: |
          python -m pipenv run pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
  deploy:
    needs: build
    name: Deploy to fly.io
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --update-only --detach
